### PR TITLE
Update About text [1]

### PR DESCRIPTION
**Pull request by stevieflow**
Updates exclusions bullet points:

- Specific activities 
- UsingAid Type

### CODE REVIEW

**Comment by davidmegginson** [comment]
Looks good.

**Comment by stevieflow** [comment]
Hi @baripembo @mcarans I can't see these changes in the production About page at https://data.humdata.org/viz-iati-c19-dashboard/about/ ...

**Comment by baripembo** [comment]
@stevieflow oh yah i need to run a deploy for you. i can do that today. for future maybe we can look into creating a github actions for this. maybe @mcarans can do this? or i can look into it as well.

**Comment by baripembo** [comment]
@stevieflow you should hopefully see your changes now!

**Comment by stevieflow** [comment]
I see it - thanks @baripembo !

**Pull request merged**
